config/routes.rb
Rails.application.routes.draw do
  get 'game/index'

  devise_for :trainers
  # root to: 'pokemon#index'
  root 'game#index'

  get 'brewery/index'

  get 'pokemon/index'

  get 'pokemon/submit'

  get 'pokemon/redirect'

  get 'pokemon/get'

  get 'brewery/get'

  get 'brewery/select'

  get 'game/new'

  get 'game/loadout'

  get 'game/battle'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brewery.rb
require 'json'
require 'httparty'
require 'redis'
# require 'beer_get_worker.rb'
# optional
require 'pry'
#
class Brewery # < ApplicationRecord
  attr_reader :name, :brewery_id, :brewery_readout, :breweries
  def initialize(options = {})
    @breweries = { 'Brews' =>
      [
        'Lonerider' => 'd25euF',
        'Raleigh' => 'ST1lih',
        'Surly' => 'cPRfoj',
        'Gizmo Brew Works' => 'ehcJKn',
        'Bull City Burger' => 'eu1cAn',
        'Trophy' => '6jDZlV',
        'Fullsteam' => 'HUCz2L',
        'Deep River' => 'bLbQyH',
        'Hi-Wire' => 'ueswRW',
        'Palmetto' => 'Fvb1JY',
        'Big Boss' => 'pwfPCD',
        'Mother Earth' => 'LZ4UuN',
        'Bond Brothers' => 'mEDZEd',
        'The Duck-Rabbit Craft' => 'rBxNNF',
        'Anderson Valley' => 'L2dAEr',
        'Cisco Brewers' => 'r5kixF', #haunter
        'Westbrook' => 'HPfwPW', #raichu
        'DuClaw' => 'TVgBWg', #Ninetails
        'Jailbreak' => 'cT18w8', #Dragonair
        'New Belgium' => 'Jt43j7', #arcanine
        'Cigar City' => 'EYuZg3' #charmander
      ]}
    @name = options['name']
    @brewery_id = @breweries['Brews'].first[@name]
    @brewery_readout = {}
  end

  def name_check
    return true if File.file?("cache/brewery/#{@name}.json")
  end

  def write_to(object)
    if Redis.current.get(@name) != nil || object.name_check == true
    else
      p "before worker"
      BeerGetWorker.perform_async(@brewery_id)
      p "end job"
    end

    @brewery_readout = Redis.current.get(@name)
    # @brewery_readout = File.read("cache/brewery/#{name}.json") if @brewery_readout == {}
  end
end

app/models/game.rb
class Game < ApplicationRecord
  def self.destroy
    redirect_to destroy_localstore_path
  end

  def destroy_localstore
  end
end

app/models/pokemon.rb
require 'json'
require 'httparty'
require 'redis'
# require_relative 'workers/poke_get_worker.rb'

class Pokemon
  attr_reader :pkmn_name, :pkmn_id, :pkmn_readout

  def initialize(options = {})
    @pkmn_name = options['name']
    @poke_list = JSON.parse(File.read('cache/pokemon/pokemon.json'))
    $all_pokemon = @poke_list['http://pokeapi.co/api/v2/pokedex/kanto']['pokemon_entries']
    pkmn_base = $all_pokemon.find { |h| h['pokemon_species']['name'] == @pkmn_name }
    @pkmn_id = pkmn_base['entry_number']
    @pkmn_readout = {}
  end

  def name_check
    return true if File.file?("cache/pokemon/#{@pkmn_name}.json")
  end

  def write_to(pkmn_object)
    if pkmn_object.name_check == true || Redis.current.get(@pkmn_name) != nil
    else
      PokeGetWorker.perform_async(@pkmn_id, @pkmn_name)
    end

    @pkmn_readout = Redis.current.get(@pkmn_name)
    # @pkmn_readout =
    #   File.read("cache/pokemon/#{@pkmn_name}.json") if @pkmn_readout == {}
  end
end


# <% pkmn_object = Pokemon.new('name' => 'zubat', 'list' => @poke_list)#, 'id_names' => pkmn_name_and_id) %>
# <% pkmn_object = pkmn_object.write_to(pkmn_object) %>
#
# <% brewery_object = Brewery.new({'name' => 'DuClaw'}) %>
# <% brewery_object = brewery_object.write_to(brewery_object) %>

app/models/trainer.rb
class Trainer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brewery_controller.rb
require 'pry'
#
class BreweryController < ApplicationController
  def index
  end

  def select
  end

  def get
    brewery_object = Brewery.new('name' => params[:brewery])
    brewery_object.write_to(brewery_object)
    respond_to do |format|
      format.json { render json: brewery_object.brewery_readout.to_json }
      format.html { redirect_to '/brewery/index' }
    end
  end
end

# possible erb form_for helper if JS doesn't start cooperating.
# <%= form_tag('/brewery/get', method: "get", class: "brewerySearch") do %>
#   <%= label_tag(:brewery, "Search for:") %>
#   <%= text_field_tag(:brewery) %>
#   <%= submit_tag("Submit", class: "beerSubmit") %>
# <% end %>

app/controllers/game_controller.rb
#
class GameController < ApplicationController
  def index
    redirect_to '/trainers/sign_in' if current_trainer.nil?
  end

  def home

  end

  def loadout
  end

  def battle
  end
end

app/controllers/pokemon_controller.rb
require 'pry'

#
class PokemonController < ApplicationController
  def index
  end

  def get
    pkmn_object = Pokemon.new('name' => params[:pokemon], 'list' => '')
    pkmn_object.write_to(pkmn_object)
    respond_to do |format|
      format.json { render json: pkmn_object.pkmn_readout.to_json }
      format.html { redirect_to '/pokemon/index' }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brewery_helper.rb
module BreweryHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/views/brewery/index.html.erb
<div class="container">
  <div class="row">
    <%= button_to "Log Out", destroy_trainer_session_path, method: :delete, :class => 'btn sharp logout pull-right', role: 'presentation'%>
    <ol class="breadcrumb col-sm-10">
      <li class="homeBtn"><a href="/game/index">Home</a></li>
      <li><a href="/pokemon/index" class="active">Pokemon</a></li>
      <li>Brewery</li>
      <li class="">Ready Up</li>
      <li class="">Battle</li>
    </ol>
  </div>
  <div class="row">
    <div class="progress">Readiness
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
        <span class="sr-only">60% Complete (success)</span>
      </div>
    </div>
  </div>
</div>

<div class="container main-body">
  <div class="row search-bars">
    <input type="text" class="form-control sharp search-bar col-sm-3" autocomplete="off" id="brewerySearch" placeholder="Enter a Brewery..."></input>
    <br />
    <button type="submit" class="btn sharp btn-default brewery-search-btn pull-left col-md-1">Search</button>
  </div>
  <br />
  <div class="beerLoadout">
    <div class="panel sharp panel-default">
      <div class="panel-heading">
        <h3 class="panel-title breweryName"></h3>
      </div>
      <div class="panel-body">
        <ul class="beerNames">
        </ul>
      </div>
    </div>

  </div>
  <a href="/game/loadout"><button type="submit" class="btn sharp pull-left btn-default brew-continue-btn col-md-1">Continue</button></a>
</div>

app/views/game/battle.html.erb
<body class="battle-page">
<div class="container">
  <div class="row">
    <%= button_to "Log Out", destroy_trainer_session_path, method: :delete, :class => 'btn sharp logout pull-right', role: 'presentation'%>
    <ol class="breadcrumb sharp col-sm-10">
      <li class="homeBtn"><a href="/game/index">Home</a></li>
      <li>Pokemon</li>
      <li>Brewery</li>
      <li>Ready Up</a></li>
      <li class="active">Battle</li>
    </ol>
  </div>

  <div class="row">
    <div class="progress sharp">
      <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
        <span class="sr-only">100% Complete</span>
      </div>
    </div>

  </div>
</div>
<ul class="pull-left userHealth">
</ul>
<ul class="pull-right enemyHealth">
</ul>
<div class="container battle-board-container">
  <h1 class="text-center pulsate"> Battle! </h1>
  <h1 class="countdown text-center"></h1>
  <div class="col-sm-6 pic">
    <div class="mew">
    </div>
    <div class="userMonPic">
    </div>
  </div>
</div>

<!-- <button type="submit" class="btn sharp btn-primary start-fight-btn col-md-2"><p>Send your 'mon in!</p> -->

app/views/game/home.html.erb
<div class"container">
  <ul class="nav nav-pills">
    <li role="presentation" class="active"><a href="/game/home">Home</a></li>
    <li role="presentation"><a href="/pokemon/index">New Pokemon</a></li>
    <li role="presentation"><a href="#">Messages</a></li>
    <li>
      <%= button_to "Log Out", destroy_trainer_session_path, method: :delete, :class => 'logout', role: 'presentation'%>
    </li>
  </ul>
</div>

app/views/game/index.html.erb
<div class="container">
  <div class="row">
    <%= button_to "Log Out", destroy_trainer_session_path, method: :delete, :class => 'btn sharp logout pull-right', role: 'presentation'%>
    <ol class="breadcrumb col-sm-10">
      <li class="homeBtn"><a href="/game/index" class="active">Home</a></li>
      <li class="">Pokemon</li>
      <li class="">Brewery</li>
      <li class="">Ready Up</li>
      <li class="">Battle</li>
    </ol>
  </div>
  <div class="row">
    <h1 class="tagline text-center"> Gotta Chug 'em All!</h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="pokeball poke-div">
      <div class="btn ready-screen-btn top poke-div"> <br />Battle
        <div class="middle_circle poke-div">
            <div class="white_in poke-div"></div>
        </div>
      </div>
    </div>
    <!-- <div class="col-sm-12">
      <a href="/game/loadout" type="submit" class="btn sharp ready-screen-btn col-md-1"><h2>Proceed to Battle Staging</h2></a>

      <a href="/pokemon/index" type="submit" class="btn sharp pokemon-selection-btn col-md-1"><h2>Pick Your 'Mon</h2></a>
    </div> -->
  </div>
  <div class="row">
    <div class="btn pokemon-selection-btn bottom poke-div"><br /> Pick a 'Mon
    </div>
  </div>
    <br />
    <div class="row">
      <div class="col-sm-12">


    </div>
  </div>
    <br />
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title poke-panel-title"></h3>
        </div>
        <div class="panel-body">
          <ul class="pokemonLoadout">
          </ul>
          <ul class="attacks-ul">
          </ul>
        </div>
      </div>
      <button type="submit" class="btn sharp btn-primary display-current-btn col-md-3"><p>View Current 'Mon</p>
    </div>

  </div>
</div>

app/views/game/loadout.html.erb
<div class="container">
  <div class="row">
    <%= button_to "Log Out", destroy_trainer_session_path, method: :delete, :class => 'btn sharp logout pull-right', role: 'presentation'%>
    <ol class="breadcrumb sharp col-sm-10">
      <li class="homeBtn"><a href="/game/index">Home</a></li>
      <li><a href="/pokemon/index" class="pkmnBtn active">Pokemon</a></li>
      <li><a href="/brewery/index" class="brewBtn active">Brewery</a></li>
      <li><a href="#" class="active">Ready Up</a></li>
      <li class="">Battle</li>
    </ol>
  </div>
  <div class="row">
    <div class="progress sharp">Readiness
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
        <span class="sr-only">80% Complete (success)</span>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="">
      <a href="/game/battle" type="submit" class="btn sharp battle-btn col-md-1"><h2 class="battle-head">Battle!</h2></a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeBrew</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Khula" rel="stylesheet">
  </head>

  <body>
    <% if current_page? '/game/battle' %>
      <div class="battle-page">
      </div>
    <% end %>

    <%= yield %>


  <div class="modal"></div>
  </body>
</html>